import{calculateChaosAction,calculateExdeathAction,calculateExdeathEyeActions,cloneState,initialState,MechanicState,normalizeMechanicState,normalizeState,phaseLabel,setExdeathMechanic}from'./domain/mechanics.js';import{createCombatEventSource}from'./services/combatEventSource.js';
const app=document.getElementById('app');
if(!app)throw new Error('App root element was not found.');
const STORAGE_KEY='umad-p4-helper-state',phases=['exdeath','chaos'];let state=load(),confirmReset=false;
function readStoredState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(error){console.error('Failed to read saved state.',error);return{}}}
function load(){const loaded=normalizeState(readStoredState());if(!phases.includes(loaded.phase))loaded.phase='exdeath';return loaded}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(error){console.error('Failed to save state.',error)}}
function setState(next){state=typeof next==='function'?next(state):{...state,...next};save();render()}
function icon(n){return`<span class="icon icon-${n}" aria-hidden="true"></span>`}
function mark(v){const stateValue=normalizeMechanicState(v);return stateValue===MechanicState.Circle?'O':stateValue===MechanicState.Question?'?':'-'}
function truth(path,value){const opts=[MechanicState.Circle,MechanicState.Question];return`<div class="truth-buttons">${opts.map(v=>`<button data-set="${path}" data-value="${v}" class="${value===v?'selected':''}">${mark(v)}</button>`).join('')}</div>`}
function orderBadge(order){return order?`<span class="order-badge" title="엑스데스 캐스팅 판정 입력 순서">${order}</span>`:''}
function row(iconName,label,path,value,result='',order=0){return`<div class="mechanic-row"><span class="mechanic-name">${icon(iconName)}${label}</span>${truth(path,value)}${result||order?`<span class="result-wrap">${orderBadge(order)}${result?`<strong class="result-pill">${result}</strong>`:''}</span>`:''}</div>`}
function eyeResult(eyes){const label={look:'보기',away:'안보기'};return`<span class="eye-results">${[0,1].map(i=>`<strong class="result-pill eye-pill ${eyes[i]?'':'pending'}">${i+1} ${eyes[i]?label[eyes[i]]:'대기'}</strong>`).join('<span class="arrow">→</span>')}</span>`}
function card(title,phase,body){return`<section class="card ${state.phase===phase?'current':''}"><div class="card-head"><span>${title}</span><b>${state.phase===phase?'현재':''}</b></div><div class="card-body">${body}</div></section>`}
function setPath(path,value){const [group,key]=path.split('.');if(group==='exdeath'){setState(s=>({...s,exdeath:setExdeathMechanic(s.exdeath,key,value)}));return}setState(s=>({...s,[group]:{...s[group],[key]:normalizeMechanicState(value)}}))}
function reset(){if(!confirmReset){confirmReset=true;setTimeout(()=>{confirmReset=false;render()},2500);render();return}state=cloneState(initialState);state.phase='exdeath';confirmReset=false;save();render()}
function exdeathOrder(mechanic){const index=state.exdeath.inputOrder.indexOf(mechanic);return index===-1?0:index+1}
function render(){const eye=calculateExdeathEyeActions(state.exdeath);app.innerHTML=`<main class="shell"><header><div><h1>요성난무 4페이즈 도우미</h1><p>작은 창용 수동 입력 헬퍼</p></div><button class="reset" data-reset>${icon('reset')}${confirmReset?'한 번 더':'초기화'}</button></header><nav>${phases.map(p=>`<button data-phase="${p}" class="${state.phase===p?'active':''}">${phaseLabel(p)}</button>`).join('')}</nav>${card('엑스데스','exdeath',`<p class="hint">물/번개/폭탄은 디버프 시간순으로 입력, 마안은 입력 순서의 O/?에서 자동 계산됩니다.</p>${row('water','물','exdeath.water',state.exdeath.water,calculateExdeathAction('water',state.exdeath.water),exdeathOrder('water'))}${row('lightning','번개','exdeath.thunder',state.exdeath.thunder,calculateExdeathAction('thunder',state.exdeath.thunder),exdeathOrder('thunder'))}${row('bomb','폭탄','exdeath.bomb',state.exdeath.bomb,calculateExdeathAction('bomb',state.exdeath.bomb),exdeathOrder('bomb'))}<div class="eye">${icon('eye')}<b>마안</b>${eyeResult(eye)}</div>`)}${card('카오스','chaos',`${row('fire','화염','chaos.fire',state.chaos.fire,calculateChaosAction('fire',state.chaos.fire))}${row('water','해일','chaos.tsunami',state.chaos.tsunami,calculateChaosAction('tsunami',state.chaos.tsunami))}`)}<section class="settings">${[['alwaysOnTop','항상 위에 표시'],['resetOnCombatEnd','전투 종료 시 자동 초기화']].map(([k,l])=>`<label><input data-setting="${k}" type="checkbox" ${state.settings[k]?'checked':''}>${l}</label>`).join('')}</section></main>`;bind()}
/* Mock 테스트 패널은 향후 재사용 가능성을 위해 렌더링/바인딩만 비활성화했습니다.
<details class="mock"><summary>${icon('connection')}Mock 테스트</summary><div>${phases.map(p=>`<button data-mock="${p}">${phaseLabel(p)}</button>`).join('')}<button data-combat-end>전투 종료</button></div></details>
*/
function bind(){document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>setPath(b.dataset.set,b.dataset.value));document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>setState({phase:b.dataset.phase}));document.querySelectorAll('[data-setting]').forEach(i=>i.onchange=()=>setState(s=>({...s,settings:{...s.settings,[i.dataset.setting]:i.checked}})));const resetButton=document.querySelector('[data-reset]');if(resetButton)resetButton.addEventListener('click',reset)/* Mock 테스트 이벤트 바인딩 비활성화: document.querySelectorAll('[data-mock]').forEach(b=>b.onclick=()=>MockCombatEventSource.emit({type:'PhaseChanged',phase:b.dataset.mock}));const combatEndButton=document.querySelector('[data-combat-end]');if(combatEndButton)combatEndButton.addEventListener('click',()=>MockCombatEventSource.emit({type:'CombatEnded'})) */}
function connectCombatEventSource(){try{createCombatEventSource().connect(ev=>{if(ev.type==='CombatEnded'&&state.settings.resetOnCombatEnd){state=cloneState(initialState);state.phase='exdeath';save();render()}if(ev.type==='PhaseChanged'&&phases.includes(ev.phase))setState({phase:ev.phase})})}catch(error){console.error('Failed to connect combat event source.',error)}}
window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='r')reset()});render();connectCombatEventSource();
